name: SimpleChatLog
description: SimpleChatLog
main: com.connorlinfoot.simplechatlog.SimpleChatLog
version: 1.2
commands:
  scl:
    description: SimpleChatLog
permissions:
  simplechatlog.reload:
    default: op